\NeedsTeXFormat{LaTeX2e}

\ProvidesClass{Algorithms}[2016/02/29 Algorithms]
%%Execute Default option

%% Process given options
\ProcessOptions\relax

%% Load base class
\LoadClass[12pt,a4Paper]{article}

%% Load Additional packages and Commands
\RequirePackage[left=2cm,right=2cm,top=2cm,bottom=2cm]{geometry}

\RequirePackage{sectsty}
\allsectionsfont{\bfseries\sffamily}

%%ends the processing
\endinput
}
