\NeedsTexFormat{LaTeX2e}
\ProvidesClass{Algorithms}{2016/02/29 Algorithms}
\DeclareOption{12pt}{
  \PassOptionsToClass{\CurrentOption}{article}
}
%%Execute Default option
\ExecuteOptions{12pt}

%% Process given options
\ProcessOptions\relax

%% Load base class
\LoadClass[a4Paper]{article}

%% Load Additional packages and Commands
\RequirePackage[left=2cm,right=2cm,top=2cm,bottom=2cm]{geometry}

\RequirePackage{titlesec}
\titleformat*{\section}{\LARGE\sfbold}
\titleformat*{\subsection}{\Large\sfbold}
\titleformat*{\subsubsection}{\large\sfbold}

%%ends the processing
\endinput
}
